name: Run Python tests

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Start app container
      run: docker compose up --detach --wait --wait-timeout 300 app || docker compose logs app
      shell: bash
    - name: Run tests
      run: docker compose exec app poetry run python -m pytest
      shell: bash
